# Copyright (c) 2025 ByteDance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release Build and Push

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    tags:
      - "v*.*.*"  # This triggers the workflow on any new tag

jobs:
  image-release-dockerhub:
    runs-on: ubuntu-22.04
    needs: [cut-github-release]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        component:
          - name: priskv
            file: docker/Dockerfile_ubuntu2204
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push ${{ matrix.component.name }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: ${{ matrix.component.file }}
          push: true
          tags: |
            aibrix/${{ matrix.component.name }}:${{ github.ref_name }}
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

  image-release-ghcr:
    runs-on: ubuntu-22.04
    needs: [cut-github-release]
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        component:
          - name: priskv
            file: docker/Dockerfile_ubuntu2404
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Login to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AIBRIX_ORG_PACKAGE_UPDATE_GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push ${{ matrix.component.name }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.component.file }}
          push: true
          tags: |
            ghcr.io/aibrix/${{ matrix.component.name }}:${{ github.ref_name }}
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

  python-wheel-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    environment:
      name: pypi
      url: https://pypi.org/p/pypriskv
    permissions:
      id-token: write
    name: publish
    env:
      CMAKE_POLICY_VERSION_MINIMUM: 3.5
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python environment ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ca-certificates \
                              gcc \
                              g++ \
                              make \
                              binutils \
                              libibverbs-dev \
                              librdmacm-dev \
                              libevent-dev \
                              libssl-dev \
                              libmount-dev \
                              libncurses5-dev \
                              libonig-dev \
                              libhiredis-dev \
                              liburing-dev

          # install cmake
          cd /tmp && \
          wget -q https://cmake.org/files/v4.1/cmake-4.1.3-linux-x86_64.sh && \
          sudo bash cmake-4.1.3-linux-x86_64.sh --skip-license --prefix=/usr && \
          rm cmake-4.1.3-linux-x86_64.sh && \
          cd -

          # libevhtp uses TestEndianess.c.in
          sudo ln -s /usr/share/cmake-4.1/Modules/TestEndianness.c.in /usr/share/cmake-4.1/Modules/TestEndianess.c.in

          # install ucx
          cd /tmp && \
          wget -q https://github.com/openucx/ucx/releases/download/v1.19.0/ucx-1.19.0-ubuntu22.04-mofed5-cuda12-x86_64.tar.bz2 && \
          tar xvf ucx-1.19.0-ubuntu22.04-mofed5-cuda12-x86_64.tar.bz2 && \
          sudo dpkg -i ucx-1.19.0.deb ucx-cuda-1.19.0.deb ucx-xpmem-1.19.0.deb && \
          rm /tmp/ucx-1.19.0-ubuntu22.04-mofed5-cuda12-x86_64.tar.bz2 /tmp/ucx-1.19.0.deb /tmp/ucx-cuda-1.19.0.deb /tmp/ucx-xpmem-1.19.0.deb && \
          cd -

          # install python dependencies
          pip install -r requirements.txt
      - name: Build
        run: |
          make pyclient
          ls -al pypriskv/dist/*
      - name: Upload release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: pypriskv/dist
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: priskv-wheels
          path: |
            pypriskv/dist/*.whl

  cut-github-release:
    runs-on: ubuntu-22.04
    needs: [python-wheel-release]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Determine if this is a prerelease based on the tag name
      # if it contains
      - name: Set Prerelease Flag
        id: prerelease_check
        run: |
          if [[ "${{ github.ref_name }}" == *"rc"* ]]; then
            echo "This is a prerelease"
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "This is not a prerelease"
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Use the tag that triggered the workflow
          name: ${{ github.ref_name }}  # The name of the release
          body: |
            Automatically generated release for tag ${{ github.ref_name }}.
          draft: true # let's always check the release before officially published.
          prerelease: ${{ env.prerelease }}
